name: 'V86 Buildroot Image Builder'
description: 'Build a v86-compatible buildroot image following the community configuration'
author: 'arcanis'

inputs:
  buildroot-config:
    description: 'Additional buildroot configuration lines to append to the base config'
    required: false
    default: ''
  copy-path:
    description: 'Path to copy into the resulting filesystem (will be copied to root of filesystem)'
    required: false
    default: ''
  buildroot-version:
    description: 'Buildroot version to use'
    required: false
    default: '2024.05.2'
  artifact-name:
    description: 'Name for the output artifact'
    required: false
    default: 'v86-buildroot-image'
  working-directory:
    description: 'Working directory for the build'
    required: false
    default: './build'

outputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: ${{ steps.build.outputs.artifact-name }}
  bzimage-path:
    description: 'Path to the built bzImage file'
    value: ${{ steps.build.outputs.bzimage-path }}

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget file cpio unzip rsync bc libncurses-dev
        
    - name: Build V86 Buildroot Image
      id: build
      shell: bash
      env:
        BUILDROOT_CONFIG: ${{ inputs.buildroot-config }}
        COPY_PATH: ${{ inputs.copy-path }}
        BUILDROOT_VERSION: ${{ inputs.buildroot-version }}
        ARTIFACT_NAME: ${{ inputs.artifact-name }}
        WORKING_DIR: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/entrypoint.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.build.outputs.bzimage-path }}
        retention-days: 30

branding:
  icon: 'cpu'
  color: 'blue'