#!/bin/sh

start() {
    echo 0 > /proc/sys/kernel/printk
    mount -a
    udhcpc
}

case "$1" in
        start)
                "$1";;
        stop|restart|reload)
                exit 0;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
