name: Example V86 Buildroot Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-basic:
    name: Build Basic Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build V86 Image
        uses: ./
        with:
          output: basic-v86-image.bin
          overlay: .github/workflows/example/overlay
          config: |
            BR2_PACKAGE_BASH=y
            BR2_SYSTEM_BIN_SH_BASH=y

            # For tput
            BR2_PACKAGE_NCURSES=y
            BR2_PACKAGE_NCURSES_TARGET_PROGS=y
          script: |
            chmod +x usr/bin/micro
          profile: |
            # Unicode symbols
            PS_SYMBOL='$'
            SEP_SYMBOL=$'\xee\[\x82\xb0\]'

            # Solarized colorscheme
            FG_OK="\\[\\e[38;5;10m\\]"
            BG_OK="\\[\\e[48;5;10m\\]"

            FG_ERR="\\[\\e[38;5;9m\\]"
            BG_ERR="\\[\\e[48;5;9m\\]"

            FG_LINE="\\[\\e[38;5;31m\\]"
            BG_LINE="\\[\\e[48;5;31m\\]"

            FG_TEXT="\\[\\e[38;5;254m\\]"

            ps1() {
              # Check the exit code of the previous command and display different
              # colors in the prompt accordingly.
              if [ "$?" -eq 0 ]; then
                local BG_EXIT="$BG_OK"
                local FG_EXIT="$FG_OK"
              else
                local BG_EXIT="$BG_ERR"
                local FG_EXIT="$FG_ERR"
              fi

              PS1="\n"
              PS1+="${FG_EXIT}${BG_EXIT}${PS_SYMBOL}${RESET}${FG_EXIT}${BG_LINE}${SEP_SYMBOL}"
              PS1+="${FG_TEXT}${BG_LINE} \\w "
              PS1+="${RESET}${FG_LINE}${SEP_SYMBOL}${RESET} "
            }

            PROMPT_COMMAND=ps1

      - name: Save as artifact
        uses: actions/upload-artifact@v4
        with:
          name: basic-v86-image
          path: basic-v86-image.bin
