name: Example V86 Buildroot Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-basic:
    name: Build Basic Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build V86 Image
        uses: ./
        with:
          artifact-name: basic-v86-image

  build-custom:
    name: Build Custom Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare custom files
        run: |
          mkdir -p custom-files/etc
          mkdir -p custom-files/usr/local/bin
          echo "Welcome to Custom V86 Linux!" > custom-files/etc/motd
          echo '#!/bin/sh' > custom-files/usr/local/bin/hello
          echo 'echo "Hello from custom script!"' >> custom-files/usr/local/bin/hello
          chmod +x custom-files/usr/local/bin/hello

      - name: Build Custom V86 Image
        uses: ./
        with:
          buildroot-config: |
            BR2_PACKAGE_PYTHON3=y
            BR2_PACKAGE_NANO=y
            BR2_PACKAGE_HTOP=y
            BR2_TARGET_ROOTFS_EXT2_SIZE="32M"
          copy-path: ./custom-files
          artifact-name: custom-v86-image