name: Test Action

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action-basic:
    name: Test Basic Build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.title, '[test]')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Basic V86 Build
        uses: ./
        with:
          artifact-name: test-basic-image
          buildroot-config: |
            # Add some small packages for testing
            BR2_PACKAGE_NANO=y

  test-action-custom:
    name: Test Custom Build
    runs-on: ubuntu-latest  
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test files
        run: |
          mkdir -p test-files/etc
          echo "Test V86 Linux Image" > test-files/etc/motd
          echo "Built with GitHub Actions" >> test-files/etc/motd

      - name: Test Custom V86 Build
        uses: ./
        with:
          buildroot-config: |
            BR2_PACKAGE_NANO=y
            BR2_PACKAGE_HTOP=y
            BR2_TARGET_ROOTFS_EXT2_SIZE="16M"
          copy-path: ./test-files
          artifact-name: test-custom-image